### ISSUE TITLE
How does the front end of the system send requests

### ISSUE THREAD

**Issue by oneSapling** [fawkes-nsdi20/fawkes#1]
Excuse me, How does the front end of the system send requests in the img

![image](https://user-images.githubusercontent.com/31071074/79250746-bb01f400-7eb1-11ea-8fd6-2a63785c30f4.png)

**Comment by ShaghayeghMrdn** [comment]
The unmodified client browser (e.g., chrome) sends a request to Fawkes backend the same way that it sends a request to the default web server. In other words, the user types the address in, after performing DNS lookup and establishing a connection to the backend, chrome sends a request to get the top-level HTML page from the backend.
